### ISSUE TITLE
Move typescript from dependencies to devDependencies

### ISSUE THREAD

**Issue by Fenntasy** [oazapfts/oazapfts#401]
Hi there,

This may be a problem depending on how the codegen is done but having `typescript` in the `dependencies` of the package mean that have `oazapfts` as a `dependency` for us will add `typescript` as our "production" dependencies.
We're using Docker so our node modules add a whole bunch of data in our resulting container (around 200mb :/).

Is there a possibility of having it switch to dev deps here?

**Comment by Xiphe** [comment]
that's not really an option since, as you've already figured, the codegen part needs it.

The solution would be splitting the package up into a codegen and a runtime part. Then you'd install `oazapfts-gen` (along with typescript) as a dev-dependency in your project  and `oazapfts-runtime` as a runtime dependency. 

This indeed is something I was thinking about for a longer time bug have not found the time to discuss this with the other maintainers and I haven't wrapped my head around it fully in terms of coming up with a migration path.

**Comment by jonkoops** [comment]
We could use NPM workspaces to create two seperate packages and publish them together.

**Comment by Xiphe** [comment]
Would appreciate when someone else could beta-test [oazapfts@6.0.0-beta.1](https://github.com/oazapfts/oazapfts/releases/tag/oazapfts-v6.0.0-beta.1) and [@oazapfts/runtime@1.0.0-beta.1](https://github.com/oazapfts/oazapfts/releases/tag/%40oazapfts%2Fruntime-v1.0.0-beta.1).

Also looking for a review on https://github.com/oazapfts/oazapfts/pull/576. It's a quite extensive changeset though 😬
