### ISSUE TITLE
Feature Request: Add option to generate zod types

### ISSUE THREAD

**Issue by SaadBazaz** [oazapfts/oazapfts#492]
Hey,
Could we have a flag to generate Zod types instead of just standard TypeScript types? APIs are usually used alongside forms, and having a form validation lib coupled with this codegen could really boost web app form capabilities.

(Based on this issue: https://github.com/reduxjs/redux-toolkit/issues/3803)

**Comment by Xiphe** [comment]
I understand where you're coming from. This would help me, too. 

That said I'm afraid that at the current stage this would blow the scope of this library. 

Maybe it might be worth exploring to split out the type generation part of this package and thereby making it also support generating zod-types. When someone would like to create something like this standalone definitely let us know.

Still I'm gonna close this issue because I don't think we can do anything about it just yet.
