### ISSUE TITLE
Enums as values

### ISSUE THREAD

**Issue by benmccann** [oazapfts/oazapfts#571]
I can use the `--useEnumType` flag to generate enums instead of union types. For example:
```
export enum JobCommand {
    Start = "start",
    Pause = "pause",
    Resume = "resume",
    Empty = "empty",
    ClearFailed = "clear-failed"
}
```

However, this won't let me reference the values in code like `JobCommand.Start`

![Screenshot from 2024-02-09 15-00-32](https://github.com/oazapfts/oazapfts/assets/322311/668cf980-84a1-4e3a-bc31-498f62f88ff1)

I'm trying to migrate from the official open api generator, which generated this:
```
export const JobCommand = {
    Start: 'start',
    Pause: 'pause',
    Resume: 'resume',
    Empty: 'empty',
    ClearFailed: 'clear-failed'
} as const;
```

**Comment by Xiphe** [comment]
Hi @benmccann 🤙

This is strange... It should™ work exactly this way and with the demo/enumApi.ts it does:

![image](https://github.com/oazapfts/oazapfts/assets/911218/1d5491d2-f42b-4048-8d98-bdc883ef993d)

I'd assume this is a problem on your end. Maybe along the lines of `import type { JobCommand }` instead of `import { JobCommand }`. Can you please double-check? 

Closing as I assume we can't help with this, please re-open when you have more infos and need adjustments on our end.

**Comment by benmccann** [comment]
Yes, I did get it working on my end: https://github.com/immich-app/immich/pull/7110. Thanks so much and sorry for the false report!
